### ISSUE TITLE
Make : image installation issues

### ISSUE THREAD

**Issue by sriramb12** [bartosz25/spark-docker#1]
Package oracle-java8-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java8-installer' has no installation candidate
The command '/bin/sh -c apt-get update &&     apt-get upgrade -y &&     apt-get install -y  software-properties-common &&     add-apt-repository ppa:webupd8team/java -y &&     apt-get update &&     echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections &&     apt-get install -y oracle-java8-installer &&     apt-get clean' returned a non-zero code: 100
make: *** [build_base_image] Error 100

how to fix this? may be some other (manual) installation steps are needed for java-8

**Comment by bartosz25** [comment]
Hi, 

Thank you for the issue. I'll try to fix it at the beginning of October. I keep the issue open meantime.

Best regards,
Bartosz.

**Comment by bartosz25** [comment]
Hi @sriramb12 

I've just pushed a fix on this branch: https://github.com/bartosz25/spark-docker/tree/fix_java_intallation_issue 
Could you retry build your project directly from it? I'll merge to the master if it works for you too (was good on my 2 laptops)

Best regards,
Bartosz.

**Comment by bartosz25** [comment]
I merged the branch with the fix  https://github.com/bartosz25/spark-docker/pull/2
